version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    expose:
      - 27017
    volumes:
      - ./data:/data/db
  rune:
    container_name: rune
    restart: always
    command: -update
    build: .
    depends_on:
      - mongo